### 测试对抗样本生成效果

In [1]:
import torch
import random
import numpy as np
import pandas as pd
import numpy as np
import foolbox as fb
from torch.utils.data import DataLoader, Subset
import torch.nn.functional as F

/root/anaconda3/envs/py39/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [8]:
log_loss_file=('./loss_log/mnist_LogisticRegressor_ntp_60000_seed_0_epochs_10_lr_0.01_wd_0.01_bs_256_optim_sgd_notransform_loss.csv')
loss_df = pd.read_csv(log_loss_file)
loss_df1 = pd.read_csv(log_loss_file)
loss_df.sort_values('loss', inplace=True, ascending=False)
loss_df1.sort_values('max', inplace=True)

In [9]:
loss_df[:30]

max  max_diff       loss   gradnorm  y_true  y_pred
24798  0.999414  0.999142  15.455508  50.742398       4       0
8729   0.964718  0.929619  14.403582  45.573702       3       7
32776  0.470431  0.017194  12.877142  34.846987       4       2
15942  0.622972  0.343417  12.786316  38.767208       4       2
26882  0.999136  0.998399  12.730476  46.971258       7       0
50514  0.987892  0.977008  12.526046  45.571205       8       3
13969  0.844480  0.761259  12.328907  37.271516       3       6
52358  0.794660  0.730476  12.324869  35.364943       2       4
18598  0.889307  0.827378  11.785258  50.020748       9       2
12679  0.977994  0.961801  11.594181  47.385070       2       8
20820  0.904971  0.823340  11.384376  48.259844       9       0
26376  0.993326  0.988460  11.342751  45.492090       1       2
7010   0.981906  0.969720  11.147221  41.797617       7       4
31134  0.957091  0.920239  10.853724  35.299149       1       2
20903  0.990780  0.984580  10.713828  43.073878       3       5
59915  0.988333  0.981281  10.507663  38.743111       4       7
22229  0.430112  0.125035  10.305344  27.363657       2       4
28357  0.915265  0.867820  10.215679  44.066140       0       8
23956  0.425483  0.118850  10.045037  40.015636       4       2
59731  0.963461  0.939017  10.041113  43.681836       5       6
2676   0.861924  0.725376   9.819124  37.418404       7       2
20735  0.998345  0.997155   9.802419  49.551294       9       0
14790  0.570660  0.337761   9.794791  33.075696       9       0
28556  0.533201  0.265067   9.775646  37.336169       4       2
46726  0.758408  0.578106   9.726549  46.978866       0       8
27155  0.998715  0.998030   9.696515  45.021970       7       2
55340  0.726037  0.519696   9.681129  35.541254       4       1
37974  0.478916  0.104312   9.384270  34.104023       2       8
44378  0.659381  0.369591   9.240301  38.256713       7       2
55739  0.653740  0.346693   9.042276  43.632380       5       2

: 

In [3]:
ordering = loss_df.index.tolist()

In [4]:
from torchvision.datasets import MNIST
from torchvision.transforms import Compose, ToTensor, Normalize, Resize, RandomCrop, RandomHorizontalFlip
train_transformation = Compose([
            ToTensor(),
            Normalize((0.1307,), (0.3081,)),
        ])
train_dataset = MNIST(root='./data', train=True, download=True, transform=train_transformation)

/root/anaconda3/envs/py39/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/root/anaconda3/envs/py39/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(


In [5]:
from models import LogisticRegressor
import os
# import foolbox as fb
device = torch.device("cuda")
model = LogisticRegressor().cuda()
model.load_state_dict(torch.load("./trained_models/mnist_LogisticRegressor_ntp_60000_seed_0_epochs_10_lr_0.01_wd_0.01_bs_256_optim_sgd_notransform.pt",map_location=torch.device('cpu')))
fmodel = fb.PyTorchModel(model, bounds=(-0.4243, 2.8216))

attack = fb.attacks.BoundaryAttack(steps=1000)
# epsilons = [0.0, 0.001, 0.01, 0.03, 0.1, 0.3, 0.5, 1.0]
# _, advs, success = attack(fmodel, images, labels, epsilons=epsilons)

/root/anaconda3/envs/py39/lib/python3.9/site-packages/foolbox/models/pytorch.py:36: UserWarning: The PyTorch model is in training mode and therefore might not be deterministic. Call the eval() method to set it in evaluation mode if this is not intended.
  warnings.warn(


In [6]:
loss_df[:20]

max  max_diff      loss  y_true  y_pred
43534  0.190383  0.005919  1.690300       8       5
53248  0.206846  0.013306  1.649633       8       2
31941  0.209251  0.020093  2.332655       4       5
41572  0.211033  0.008850  3.055791       6       8
34542  0.213539  0.025656  2.352729       1       9
45576  0.219966  0.002706  1.701481       8       5
16964  0.220727  0.015450  1.510830       8       8
43062  0.221132  0.010964  1.559852       8       9
54883  0.221831  0.003623  1.607535       5       1
45348  0.226111  0.004921  1.508731       2       3
47403  0.226933  0.002503  1.483101       9       9
32747  0.226992  0.008466  2.073409       8       7
17663  0.229693  0.005822  1.706925       2       5
24668  0.230107  0.005090  1.811057       4       9
1812   0.230533  0.048630  1.704282       4       8
9924   0.231133  0.059602  2.534626       8       1
4006   0.232161  0.070815  2.135286       8       5
8300   0.232228  0.000524  1.462295       8       5
25968  0.234486  0.012103  1.693326       8       5
16025  0.234821  0.013974  2.144610       2       3

In [7]:
ordering_dataset = Subset(train_dataset, ordering[:20])
attack_loader = torch.utils.data.DataLoader(ordering_dataset, batch_size=1, pin_memory=True,
                                              shuffle=False, num_workers=4)
for image, label in attack_loader:
    print(label)
    image, label = image.to(device), label.to(device)
    logits = model(image)
    y_pred = F.softmax(logits, dim=1)
    top_probs, y_top = torch.topk(y_pred, 1)
    y_pred = y_top[0]
    print(y_pred)
    epsilons = [0.0, 0.001, 0.01, 0.03, 0.1, 0.3, 0.5, 1.0]
    _, advs, success = attack(fmodel, image, y_pred, epsilons=epsilons)
    print(success)

tensor([8])
tensor([5], device='cuda:0')
tensor([[False],
        [False],
        [False],
        [False],
        [False],
        [ True],
        [ True],
        [ True]], device='cuda:0')
tensor([8])
tensor([2], device='cuda:0')
tensor([[False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [ True],
        [ True]], device='cuda:0')
tensor([4])
tensor([5], device='cuda:0')
tensor([[False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [ True],
        [ True]], device='cuda:0')
tensor([6])
tensor([8], device='cuda:0')
tensor([[False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False]], device='cuda:0')
tensor([1])
tensor([9], device='cuda:0')
tensor([[False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [ True]], device='cuda:0')
tensor([8])
tensor([5], d